name: Deploy Static Site with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Environment Variables in JS
        run: |
          # Replace the placeholder in your JS file with the actual Blynk token from GitHub Secrets
          sed -i 's/__BLYNK_TOKEN__/${{ secrets.BLYNK_TOKEN }}/g' ./script.js

      - name: Debug - Show script.js content
        run: cat ./script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
