name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "BLYNK_TOKEN=${{ secrets.BLYNK_TOKEN }}" > .env  # Write secret to .env file
          npm run build  # Run your build process

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Update to your output folder (e.g., dist or build)
